/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package EndpointTests

import com.github.kittinunf.fuel.gson.jsonBody
import com.github.kittinunf.fuel.gson.responseObject
import kotlin.test.Test
import com.github.kittinunf.fuel.httpGet
import com.github.kittinunf.fuel.httpPost
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class EndpointTests {
    private val statusUrl = "http://localhost:8000/status"
    private val tasksUrl = "http://localhost:8000/tasks"
    @Test fun `Test an added task is returned via get`() {
        TodoData().addTask("wow", 1)
        val (_, _, result) = tasksUrl.httpGet().responseObject<TodoList>()
        val taskList = result.get()
        assertTrue(taskList.tasks.any {
            it.text == "wow" && it.priority == 1
        })
    }

    @Test fun `Test adding via post`() {
        val jsonData = mapOf<String, Any>("text" to "Wowza", "priority" to 2)
        val (_, resp, _) = tasksUrl.httpPost().jsonBody(jsonData).response()
        assertEquals(200, resp.statusCode)
    }

    @Test fun `Test status`() {
        val (_, resp, result) = statusUrl.httpGet().responseString()
        assertEquals(200, resp.statusCode)
        assertEquals("ok", result.get())
    }
}
